# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage1/fs1/yajiey/Active/Thomas/Aperture4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage1/fs1/yajiey/Active/Thomas/Aperture4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"fmt_core\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage1/fs1/yajiey/Active/Thomas/Aperture4/CMakeFiles /storage1/fs1/yajiey/Active/Thomas/Aperture4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage1/fs1/yajiey/Active/Thomas/Aperture4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f deps/fmt/CMakeFiles/fmt.dir/build.make deps/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f deps/catch/src/CMakeFiles/Catch2.dir/build.make deps/catch/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f deps/catch/src/CMakeFiles/Catch2WithMain.dir/build.make deps/catch/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named Aperture

# Build rule for target.
Aperture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aperture
.PHONY : Aperture

# fast build rule for target.
Aperture/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Aperture.dir/build.make src/CMakeFiles/Aperture.dir/build
.PHONY : Aperture/fast

#=============================================================================
# Target rules for targets named Aperture_dev

# Build rule for target.
Aperture_dev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aperture_dev
.PHONY : Aperture_dev

# fast build rule for target.
Aperture_dev/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Aperture_dev.dir/build.make src/CMakeFiles/Aperture_dev.dir/build
.PHONY : Aperture_dev/fast

#=============================================================================
# Target rules for targets named problems

# Build rule for target.
problems: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 problems
.PHONY : problems

# fast build rule for target.
problems/fast:
	$(MAKE) $(MAKESILENT) -f problems/CMakeFiles/problems.dir/build.make problems/CMakeFiles/problems.dir/build
.PHONY : problems/fast

#=============================================================================
# Target rules for targets named test_particle

# Build rule for target.
test_particle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_particle
.PHONY : test_particle

# fast build rule for target.
test_particle/fast:
	$(MAKE) $(MAKESILENT) -f problems/examples/src/CMakeFiles/test_particle.dir/build.make problems/examples/src/CMakeFiles/test_particle.dir/build
.PHONY : test_particle/fast

#=============================================================================
# Target rules for targets named em_wave

# Build rule for target.
em_wave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 em_wave
.PHONY : em_wave

# fast build rule for target.
em_wave/fast:
	$(MAKE) $(MAKESILENT) -f problems/examples/src/CMakeFiles/em_wave.dir/build.make problems/examples/src/CMakeFiles/em_wave.dir/build
.PHONY : em_wave/fast

#=============================================================================
# Target rules for targets named sph_wave_vacuum

# Build rule for target.
sph_wave_vacuum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sph_wave_vacuum
.PHONY : sph_wave_vacuum

# fast build rule for target.
sph_wave_vacuum/fast:
	$(MAKE) $(MAKESILENT) -f problems/sph_wave_test/src/CMakeFiles/sph_wave_vacuum.dir/build.make problems/sph_wave_test/src/CMakeFiles/sph_wave_vacuum.dir/build
.PHONY : sph_wave_vacuum/fast

#=============================================================================
# Target rules for targets named pml_test

# Build rule for target.
pml_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pml_test
.PHONY : pml_test

# fast build rule for target.
pml_test/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/pml_test.dir/build.make problems/debug/src/CMakeFiles/pml_test.dir/build
.PHONY : pml_test/fast

#=============================================================================
# Target rules for targets named gca_test

# Build rule for target.
gca_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gca_test
.PHONY : gca_test

# fast build rule for target.
gca_test/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/gca_test.dir/build.make problems/debug/src/CMakeFiles/gca_test.dir/build
.PHONY : gca_test/fast

#=============================================================================
# Target rules for targets named phase_space_test

# Build rule for target.
phase_space_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase_space_test
.PHONY : phase_space_test

# fast build rule for target.
phase_space_test/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/phase_space_test.dir/build.make problems/debug/src/CMakeFiles/phase_space_test.dir/build
.PHONY : phase_space_test/fast

#=============================================================================
# Target rules for targets named IC_test

# Build rule for target.
IC_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IC_test
.PHONY : IC_test

# fast build rule for target.
IC_test/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/IC_test.dir/build.make problems/debug/src/CMakeFiles/IC_test.dir/build
.PHONY : IC_test/fast

#=============================================================================
# Target rules for targets named IC_single

# Build rule for target.
IC_single: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IC_single
.PHONY : IC_single

# fast build rule for target.
IC_single/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/IC_single.dir/build.make problems/debug/src/CMakeFiles/IC_single.dir/build
.PHONY : IC_single/fast

#=============================================================================
# Target rules for targets named gca_test_compare

# Build rule for target.
gca_test_compare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gca_test_compare
.PHONY : gca_test_compare

# fast build rule for target.
gca_test_compare/fast:
	$(MAKE) $(MAKESILENT) -f problems/debug/src/CMakeFiles/gca_test_compare.dir/build.make problems/debug/src/CMakeFiles/gca_test_compare.dir/build
.PHONY : gca_test_compare/fast

#=============================================================================
# Target rules for targets named two_stream

# Build rule for target.
two_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_stream
.PHONY : two_stream

# fast build rule for target.
two_stream/fast:
	$(MAKE) $(MAKESILENT) -f problems/two_stream/src/CMakeFiles/two_stream.dir/build.make problems/two_stream/src/CMakeFiles/two_stream.dir/build
.PHONY : two_stream/fast

#=============================================================================
# Target rules for targets named two_stream_1d

# Build rule for target.
two_stream_1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_stream_1d
.PHONY : two_stream_1d

# fast build rule for target.
two_stream_1d/fast:
	$(MAKE) $(MAKESILENT) -f problems/two_stream/src/CMakeFiles/two_stream_1d.dir/build.make problems/two_stream/src/CMakeFiles/two_stream_1d.dir/build
.PHONY : two_stream_1d/fast

#=============================================================================
# Target rules for targets named single_stream

# Build rule for target.
single_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 single_stream
.PHONY : single_stream

# fast build rule for target.
single_stream/fast:
	$(MAKE) $(MAKESILENT) -f problems/two_stream/src/CMakeFiles/single_stream.dir/build.make problems/two_stream/src/CMakeFiles/single_stream.dir/build
.PHONY : single_stream/fast

#=============================================================================
# Target rules for targets named reconnection

# Build rule for target.
reconnection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reconnection
.PHONY : reconnection

# fast build rule for target.
reconnection/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/reconnection.dir/build.make problems/reconnection/src/CMakeFiles/reconnection.dir/build
.PHONY : reconnection/fast

#=============================================================================
# Target rules for targets named no_cooling

# Build rule for target.
no_cooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 no_cooling
.PHONY : no_cooling

# fast build rule for target.
no_cooling/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/no_cooling.dir/build.make problems/reconnection/src/CMakeFiles/no_cooling.dir/build
.PHONY : no_cooling/fast

#=============================================================================
# Target rules for targets named cooling

# Build rule for target.
cooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cooling
.PHONY : cooling

# fast build rule for target.
cooling/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/cooling.dir/build.make problems/reconnection/src/CMakeFiles/cooling.dir/build
.PHONY : cooling/fast

#=============================================================================
# Target rules for targets named cooling_3d

# Build rule for target.
cooling_3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cooling_3d
.PHONY : cooling_3d

# fast build rule for target.
cooling_3d/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/cooling_3d.dir/build.make problems/reconnection/src/CMakeFiles/cooling_3d.dir/build
.PHONY : cooling_3d/fast

#=============================================================================
# Target rules for targets named ffe_kn

# Build rule for target.
ffe_kn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffe_kn
.PHONY : ffe_kn

# fast build rule for target.
ffe_kn/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/ffe_kn.dir/build.make problems/reconnection/src/CMakeFiles/ffe_kn.dir/build
.PHONY : ffe_kn/fast

#=============================================================================
# Target rules for targets named harris_kn

# Build rule for target.
harris_kn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harris_kn
.PHONY : harris_kn

# fast build rule for target.
harris_kn/fast:
	$(MAKE) $(MAKESILENT) -f problems/reconnection/src/CMakeFiles/harris_kn.dir/build.make problems/reconnection/src/CMakeFiles/harris_kn.dir/build
.PHONY : harris_kn/fast

#=============================================================================
# Target rules for targets named gr_2d_kerr_schild

# Build rule for target.
gr_2d_kerr_schild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gr_2d_kerr_schild
.PHONY : gr_2d_kerr_schild

# fast build rule for target.
gr_2d_kerr_schild/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/gr_2d_kerr_schild.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/gr_2d_kerr_schild.dir/build
.PHONY : gr_2d_kerr_schild/fast

#=============================================================================
# Target rules for targets named grpic

# Build rule for target.
grpic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpic
.PHONY : grpic

# fast build rule for target.
grpic/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/grpic.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/grpic.dir/build
.PHONY : grpic/fast

#=============================================================================
# Target rules for targets named monopole

# Build rule for target.
monopole: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monopole
.PHONY : monopole

# fast build rule for target.
monopole/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/monopole.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/monopole.dir/build
.PHONY : monopole/fast

#=============================================================================
# Target rules for targets named gap

# Build rule for target.
gap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gap
.PHONY : gap

# fast build rule for target.
gap/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/gap.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/gap.dir/build
.PHONY : gap/fast

#=============================================================================
# Target rules for targets named vacuum_wald

# Build rule for target.
vacuum_wald: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vacuum_wald
.PHONY : vacuum_wald

# fast build rule for target.
vacuum_wald/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/vacuum_wald.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/vacuum_wald.dir/build
.PHONY : vacuum_wald/fast

#=============================================================================
# Target rules for targets named gr_single_ptc

# Build rule for target.
gr_single_ptc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gr_single_ptc
.PHONY : gr_single_ptc

# fast build rule for target.
gr_single_ptc/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/gr_single_ptc.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/gr_single_ptc.dir/build
.PHONY : gr_single_ptc/fast

#=============================================================================
# Target rules for targets named torus

# Build rule for target.
torus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 torus
.PHONY : torus

# fast build rule for target.
torus/fast:
	$(MAKE) $(MAKESILENT) -f problems/gr_2d_kerr_schild/src/CMakeFiles/torus.dir/build.make problems/gr_2d_kerr_schild/src/CMakeFiles/torus.dir/build
.PHONY : torus/fast

#=============================================================================
# Target rules for targets named magnetar

# Build rule for target.
magnetar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magnetar
.PHONY : magnetar

# fast build rule for target.
magnetar/fast:
	$(MAKE) $(MAKESILENT) -f problems/magnetar/src/CMakeFiles/magnetar.dir/build.make problems/magnetar/src/CMakeFiles/magnetar.dir/build
.PHONY : magnetar/fast

#=============================================================================
# Target rules for targets named magnetar_single_ptc

# Build rule for target.
magnetar_single_ptc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magnetar_single_ptc
.PHONY : magnetar_single_ptc

# fast build rule for target.
magnetar_single_ptc/fast:
	$(MAKE) $(MAKESILENT) -f problems/magnetar/src/CMakeFiles/magnetar_single_ptc.dir/build.make problems/magnetar/src/CMakeFiles/magnetar_single_ptc.dir/build
.PHONY : magnetar_single_ptc/fast

#=============================================================================
# Target rules for targets named magnetar_single_ptc_gca

# Build rule for target.
magnetar_single_ptc_gca: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magnetar_single_ptc_gca
.PHONY : magnetar_single_ptc_gca

# fast build rule for target.
magnetar_single_ptc_gca/fast:
	$(MAKE) $(MAKESILENT) -f problems/magnetar/src/CMakeFiles/magnetar_single_ptc_gca.dir/build.make problems/magnetar/src/CMakeFiles/magnetar_single_ptc_gca.dir/build
.PHONY : magnetar_single_ptc_gca/fast

#=============================================================================
# Target rules for targets named magnetar_flux_tube

# Build rule for target.
magnetar_flux_tube: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magnetar_flux_tube
.PHONY : magnetar_flux_tube

# fast build rule for target.
magnetar_flux_tube/fast:
	$(MAKE) $(MAKESILENT) -f problems/magnetar/src/CMakeFiles/magnetar_flux_tube.dir/build.make problems/magnetar/src/CMakeFiles/magnetar_flux_tube.dir/build
.PHONY : magnetar_flux_tube/fast

#=============================================================================
# Target rules for targets named parker

# Build rule for target.
parker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parker
.PHONY : parker

# fast build rule for target.
parker/fast:
	$(MAKE) $(MAKESILENT) -f problems/parker/src/CMakeFiles/parker.dir/build.make problems/parker/src/CMakeFiles/parker.dir/build
.PHONY : parker/fast

#=============================================================================
# Target rules for targets named alfven_wave_2d

# Build rule for target.
alfven_wave_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alfven_wave_2d
.PHONY : alfven_wave_2d

# fast build rule for target.
alfven_wave_2d/fast:
	$(MAKE) $(MAKESILENT) -f problems/alfven_wave_2d/src/CMakeFiles/alfven_wave_2d.dir/build.make problems/alfven_wave_2d/src/CMakeFiles/alfven_wave_2d.dir/build
.PHONY : alfven_wave_2d/fast

#=============================================================================
# Target rules for targets named two_stream_vlasov_1d

# Build rule for target.
two_stream_vlasov_1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_stream_vlasov_1d
.PHONY : two_stream_vlasov_1d

# fast build rule for target.
two_stream_vlasov_1d/fast:
	$(MAKE) $(MAKESILENT) -f problems/vlasov_test/src/CMakeFiles/two_stream_vlasov_1d.dir/build.make problems/vlasov_test/src/CMakeFiles/two_stream_vlasov_1d.dir/build
.PHONY : two_stream_vlasov_1d/fast

#=============================================================================
# Target rules for targets named fast_wave_2d

# Build rule for target.
fast_wave_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_wave_2d
.PHONY : fast_wave_2d

# fast build rule for target.
fast_wave_2d/fast:
	$(MAKE) $(MAKESILENT) -f problems/fast_wave_2d/src/CMakeFiles/fast_wave_2d.dir/build.make problems/fast_wave_2d/src/CMakeFiles/fast_wave_2d.dir/build
.PHONY : fast_wave_2d/fast

#=============================================================================
# Target rules for targets named fast_wave_2d_cooling

# Build rule for target.
fast_wave_2d_cooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_wave_2d_cooling
.PHONY : fast_wave_2d_cooling

# fast build rule for target.
fast_wave_2d_cooling/fast:
	$(MAKE) $(MAKESILENT) -f problems/fast_wave_2d/src/CMakeFiles/fast_wave_2d_cooling.dir/build.make problems/fast_wave_2d/src/CMakeFiles/fast_wave_2d_cooling.dir/build
.PHONY : fast_wave_2d_cooling/fast

#=============================================================================
# Target rules for targets named fast_wave_2d_cartesian

# Build rule for target.
fast_wave_2d_cartesian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_wave_2d_cartesian
.PHONY : fast_wave_2d_cartesian

# fast build rule for target.
fast_wave_2d_cartesian/fast:
	$(MAKE) $(MAKESILENT) -f problems/fast_wave_2d_cartesian/src/CMakeFiles/fast_wave_2d_cartesian.dir/build.make problems/fast_wave_2d_cartesian/src/CMakeFiles/fast_wave_2d_cartesian.dir/build
.PHONY : fast_wave_2d_cartesian/fast

#=============================================================================
# Target rules for targets named fast_wave_3d_cartesian

# Build rule for target.
fast_wave_3d_cartesian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_wave_3d_cartesian
.PHONY : fast_wave_3d_cartesian

# fast build rule for target.
fast_wave_3d_cartesian/fast:
	$(MAKE) $(MAKESILENT) -f problems/fast_wave_3d_cartesian/src/CMakeFiles/fast_wave_3d_cartesian.dir/build.make problems/fast_wave_3d_cartesian/src/CMakeFiles/fast_wave_3d_cartesian.dir/build
.PHONY : fast_wave_3d_cartesian/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/check.dir/build.make tests/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named tests_dev

# Build rule for target.
tests_dev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests_dev
.PHONY : tests_dev

# fast build rule for target.
tests_dev/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests_dev.dir/build.make tests/CMakeFiles/tests_dev.dir/build
.PHONY : tests_dev/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_tests.dir/build.make tests/CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named test_exporter_snapshot

# Build rule for target.
test_exporter_snapshot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_exporter_snapshot
.PHONY : test_exporter_snapshot

# fast build rule for target.
test_exporter_snapshot/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_exporter_snapshot.dir/build.make tests/CMakeFiles/test_exporter_snapshot.dir/build
.PHONY : test_exporter_snapshot/fast

#=============================================================================
# Target rules for targets named test_exporter_mpi

# Build rule for target.
test_exporter_mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_exporter_mpi
.PHONY : test_exporter_mpi

# fast build rule for target.
test_exporter_mpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_exporter_mpi.dir/build.make tests/CMakeFiles/test_exporter_mpi.dir/build
.PHONY : test_exporter_mpi/fast

#=============================================================================
# Target rules for targets named test_mpi2d

# Build rule for target.
test_mpi2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mpi2d
.PHONY : test_mpi2d

# fast build rule for target.
test_mpi2d/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mpi2d.dir/build.make tests/CMakeFiles/test_mpi2d.dir/build
.PHONY : test_mpi2d/fast

#=============================================================================
# Target rules for targets named test_sync_ic

# Build rule for target.
test_sync_ic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sync_ic
.PHONY : test_sync_ic

# fast build rule for target.
test_sync_ic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sync_ic.dir/build.make tests/CMakeFiles/test_sync_ic.dir/build
.PHONY : test_sync_ic/fast

#=============================================================================
# Target rules for targets named test_sync_sph

# Build rule for target.
test_sync_sph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sync_sph
.PHONY : test_sync_sph

# fast build rule for target.
test_sync_sph/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sync_sph.dir/build.make tests/CMakeFiles/test_sync_sph.dir/build
.PHONY : test_sync_sph/fast

#=============================================================================
# Target rules for targets named test_sync_polarization

# Build rule for target.
test_sync_polarization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sync_polarization
.PHONY : test_sync_polarization

# fast build rule for target.
test_sync_polarization/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sync_polarization.dir/build.make tests/CMakeFiles/test_sync_polarization.dir/build
.PHONY : test_sync_polarization/fast

#=============================================================================
# Target rules for targets named test_inverse_compton

# Build rule for target.
test_inverse_compton: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_inverse_compton
.PHONY : test_inverse_compton

# fast build rule for target.
test_inverse_compton/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_inverse_compton.dir/build.make tests/CMakeFiles/test_inverse_compton.dir/build
.PHONY : test_inverse_compton/fast

#=============================================================================
# Target rules for targets named test_ic_gpu

# Build rule for target.
test_ic_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ic_gpu
.PHONY : test_ic_gpu

# fast build rule for target.
test_ic_gpu/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ic_gpu.dir/build.make tests/CMakeFiles/test_ic_gpu.dir/build
.PHONY : test_ic_gpu/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... problems"
	@echo "... run_tests"
	@echo "... Aperture"
	@echo "... Aperture_dev"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... IC_single"
	@echo "... IC_test"
	@echo "... alfven_wave_2d"
	@echo "... cooling"
	@echo "... cooling_3d"
	@echo "... em_wave"
	@echo "... fast_wave_2d"
	@echo "... fast_wave_2d_cartesian"
	@echo "... fast_wave_2d_cooling"
	@echo "... fast_wave_3d_cartesian"
	@echo "... ffe_kn"
	@echo "... fmt"
	@echo "... gap"
	@echo "... gca_test"
	@echo "... gca_test_compare"
	@echo "... gr_2d_kerr_schild"
	@echo "... gr_single_ptc"
	@echo "... grpic"
	@echo "... harris_kn"
	@echo "... magnetar"
	@echo "... magnetar_flux_tube"
	@echo "... magnetar_single_ptc"
	@echo "... magnetar_single_ptc_gca"
	@echo "... monopole"
	@echo "... no_cooling"
	@echo "... parker"
	@echo "... phase_space_test"
	@echo "... pml_test"
	@echo "... reconnection"
	@echo "... single_stream"
	@echo "... sph_wave_vacuum"
	@echo "... test_exporter_mpi"
	@echo "... test_exporter_snapshot"
	@echo "... test_ic_gpu"
	@echo "... test_inverse_compton"
	@echo "... test_mpi2d"
	@echo "... test_particle"
	@echo "... test_sync_ic"
	@echo "... test_sync_polarization"
	@echo "... test_sync_sph"
	@echo "... tests"
	@echo "... tests_dev"
	@echo "... torus"
	@echo "... two_stream"
	@echo "... two_stream_1d"
	@echo "... two_stream_vlasov_1d"
	@echo "... vacuum_wald"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

